debate/api/urls.py
from django.conf.urls import url
from django.contrib import admin
from debate.api.views import (
    DebateTopicListAPIView,
    DebateTopicDetailAPIView,
    DebateTopicEditAPIView,
    DebateTopicDeleteAPIView
)

urlpatterns = [
    url(r'^$', DebateTopicListAPIView.as_view(), name='debate-list'),
    url(r'^(?P<pk>\d+)/$', DebateTopicDetailAPIView.as_view(), name='debate-list'),
    url(r'^(?P<pk>\d+)/edit/$', DebateTopicEditAPIView.as_view(), name='debate-update'),
    url(r'^(?P<pk>\d+)/delete/$', DebateTopicDeleteAPIView.as_view(), name='debate-delete')

]

debate/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth.views import login, logout

app_name = 'debate'

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'debate/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'debate/logout.html'}, name='logout'),
    url(r'^register/$', views.Register.as_view(), name='register'),
    url(r'^register/user_profile/$', views.RegisterUserProfile.as_view(), name='register_user_profile'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileView.as_view(), name='profile_with_pk'),
    url(r'^profile/edit/$', views.profile_edit, name='profile_edit'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends, name='change_friends'),
    url(r'^find_friends/$', views.FindFriends.as_view(), name='find_friends'),

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^debate-topic/add/$', views.DebateTopicCreate.as_view(),name='debate-topic-add'),
    url(r'^debate-topic/(?P<pk>[0-9]+)/$', views.DebateTopicCreate.as_view(),name='debate-topic-update'),
    url(r'^debate-topic/(?P<pk>[0-9]+)/delete/$', views.DebateTopicCreate.as_view(),name='debate-topic-delete'),

    url(r'^(?P<pk>[0-9]+)/comment-add/$', views.add_comment_to_post, name='comment-add'),

    url(r'^search/', views.search_titles),

    url(r'^api/', include('debate.api.urls', namespace='debate-api')),
    url(r'^friendship/', include('friendship.urls')),
]

debateIt/urls.py
#masterDebater URL Configuration

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'debate/', include('debate.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^blog/comments/', include('fluent_comments.urls')),
    url(r'^comments/', include('django_comments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

debate/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from multiselectfield import MultiSelectField
from django.utils import timezone
from awesome_avatar.fields import AvatarField

#USER
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    city = models.CharField(max_length=40, null=True)
    email = models.EmailField(max_length=60, null=True)
    image = models.ImageField(upload_to='profile_image', blank=True)
    # image = AvatarField(upload_to='avatars', width=100, height=100, blank=True)
    TOPIC_CHOICES = (('Sports', 'Sports'),
                     ('Politics', 'Politics'),
                     ('Entertainment', 'Entertainment'),
                     ('Fashion', 'Fashion'),
                     ('Odd News', 'Odd News'),
                     ('Local', 'Local'),
                     ('International', 'International'),
                     ('Music', 'Music'),
                     ('Trending', 'Trending'),
                     ('Technology', 'Technology'),
                     ('Science', 'Science'),
                     ('Business', 'Business'),
                     ('Finance', 'Finance'),
                     ('Television', 'Television'),
                     ('Movies', 'Movies'),
                     ('Celebrities', 'Celebrities'),
                     ('Social Media', 'Social Media'),
                     ('Food', 'Food'),
                     ('Health', 'Health'),
                     ('Nature', 'Nature'),
                     ('Kids', 'Kids'),
                     ('Breaking News', 'Breaking News'),
                     ('Travel', 'Travel'),
                     ('Substances', 'Substances'),
                     ('United States', 'United States'),
                     ('Andimals', 'Animals'),
                     ('Art', 'Art'),
                     ('Education', 'Education'),
                     ('Employment', 'Employment'),
                     ('Brands', 'Brands')
                     )
    favorite_topics = MultiSelectField(choices=TOPIC_CHOICES, default=(('Odd News', 'Odd News')))


    def __str__(self):
        return self.user.username



def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)
User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def remove_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)


#DEBATE CLASSES

class Community(models.Model):
    name = models.CharField(max_length=150)
    description = description = models.CharField(max_length=350)
    photo = models.ImageField(blank=True)
    host = models.ForeignKey(User)

class DebateTopic(models.Model):
    topic = models.CharField(max_length=150)
    description = models.CharField(max_length=350)
    timestamp = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(blank=True)
    article_URL = models.URLField(blank=True, null=True)
    user = models.ForeignKey(User)


    TOPIC_CHOICES = (('Sports', 'Sports'),
                     ('Politics', 'Politics'),
                     ('Entertainment', 'Entertainment'),
                     ('Fashion', 'Fashion'),
                     ('Odd News', 'Odd News'),
                     ('Local', 'Local'),
                     ('International', 'International'),
                     ('Music', 'Music'),
                     ('Trending', 'Trending'),
                     ('Technology', 'Technology'),
                     ('Science', 'Science'),
                     ('Business', 'Business'),
                     ('Finance', 'Finance'),
                     ('Television', 'Television'),
                     ('Movies', 'Movies'),
                     ('Celebrities', 'Celebrities'),
                     ('Social Media', 'Social Media'),
                     ('Food', 'Food'),
                     ('Health', 'Health'),
                     ('Nature', 'Nature'),
                     ('Kids', 'Kids'),
                     ('Breaking News', 'Breaking News'),
                     ('Travel', 'Travel'),
                     ('Substances', 'Substances'),
                     ('United States', 'United States'),
                     ('Andimals', 'Animals'),
                     ('Art', 'Art'),
                     ('Education', 'Education'),
                     ('Employment', 'Employment'),
                     ('Brands', 'Brands')
                     )
    tags = MultiSelectField(choices=TOPIC_CHOICES, default=(('Odd News', 'Odd News')))


    def get_absolute_url(self):
        return reverse('debate:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.topic

class DebateSide(models.Model):
    debate_topic = models.ForeignKey(DebateTopic, on_delete=models.CASCADE)
    side = models.CharField(max_length=250)
    side_points = models.BigIntegerField()

    def __str__(self):
        return self.side


#a point is a claim, or comment, on the debate. It's how other contribute.
class Point(models.Model):
    debate = models.ForeignKey(DebateTopic, on_delete=models.CASCADE, related_name='points', null=True)
    # debate_side = models.ForeignKey(DebateSide)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    claim = models.CharField(max_length=500)
    good_points = models.BigIntegerField(default=0)  #likes
    bad_points = models.BigIntegerField(default=0)   #dislikes

    def __str__(self):
        return self.claim

debate/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile, Point
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from multiselectfield import MultiSelectField
from fluent_comments.forms import CompactLabelsCommentForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
    )

    # def save(self, commit=True):
    #     user = super(RegistrationForm, self).save(commit=False)
    #     user.first_name = self.cleaned_data['first_name']
    #     user.last_name = self.cleaned_data['last_name']
    #     user.email = self.cleaned_data['email']
    #
    #     if commit:
    #         user.save()
    #
    #     return user

class UserProfileRegForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    city = forms.CharField(required=True)
    forms.CharField()
    favorite_topics = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                             choices=UserProfile.TOPIC_CHOICES)



    class Meta:
        model = UserProfile
        fields = (
            'image',
            'city',
            'favorite_topics'
        )


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )



class CommentForm(forms.ModelForm):

    class Meta:
        model = Point
        fields = ('claim',)


class CommentForm(CompactLabelsCommentForm):
    """
    The comment form to use
    """

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['url'].label = "Website"  # Changed the label
        self.fields['name'] = User

debate/api/views.py
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    DestroyAPIView,
    UpdateAPIView
    )
from debate.models import DebateTopic
from debate.api.serializers import DebateTopicSerializer

class DebateTopicListAPIView(ListAPIView):
    queryset = DebateTopic.objects.all()
    serializer_class = DebateTopicSerializer

class DebateTopicDetailAPIView(RetrieveAPIView):
    queryset = DebateTopic.objects.all()
    serializer_class = DebateTopicSerializer

class DebateTopicEditAPIView(UpdateAPIView):
    queryset = DebateTopic.objects.all()
    serializer_class = DebateTopicSerializer

class DebateTopicDeleteAPIView(DestroyAPIView):
    queryset = DebateTopic.objects.all()
    serializer_class = DebateTopicSerializer

debate/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.http import HttpResponse, Http404
from .models import DebateTopic, Friend, Point
from django.template import loader
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView, View
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
from .forms import RegistrationForm, EditProfileForm, UserProfileRegForm, CommentForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserChangeForm
from django.urls import reverse
from haystack.query import SearchQuerySet
from django.contrib.auth.models import User
from friendship.models import Friend, Follow

#Generic view classes
class IndexView(generic.ListView):
    template_name = "debate/index.html"

    def get_queryset(self):
        return DebateTopic.objects.all()

class FindFriends(generic.ListView):
    template_name = "debate/find_friends.html"

    def get_queryset(self):
        return User.objects.all().exclude(username=self.request.user.username)

class DetailView(generic.DetailView):
    model = DebateTopic
    template_name = "debate/detail.html"

#DebateTopic view classes
class DebateTopicCreate(CreateView):
    model = DebateTopic
    fields = ['topic', 'description', 'article_URL', 'photo', 'tags']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(DebateTopicCreate, self).form_valid(form)

class DebateTopicEdit(UpdateView):
    model = DebateTopic
    fields = ['topic', 'description']

class DebateTopicDelete(DeleteView):
    model = DebateTopic
    success_url = reverse_lazy('debate:index')

#register view func
class Register(View):
    template_name = 'debate/reg_form.html'
    form_class = RegistrationForm

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']

            user.set_password(password)
            user.save()


            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('/debate/register/user_profile/')
        return render(request, self.template_name, {'form':form})

class RegisterUserProfile(View):
    template_name = 'debate/profile_reg_form.html'
    form_class = UserProfileRegForm

    def get(self, request):
        user = request.user
        userprofile = request.user.profile
        form = self.form_class(request.POST, instance=userprofile)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()

            return redirect('/debate')
        return render(request, self.template_name, {'form': form})




#debate view func
class ProfileView(generic.TemplateView):
    template_name = "debate/profile.html"

    def get(self, request, **kwargs):
        task_id = self.kwargs.get('pk', None)
        if task_id:
            user = User.objects.get(pk=task_id)
        else:
            user = request.user
        user_debates = user.debatetopic_set.all()
        # friend = Friend.objects.get(current_user=request.user)
        # friends = friend.users.all().order_by('first_name', 'last_name')
        get_friends = Friend.objects.friends(request.user)
        args = {'user' : user,  'user_debates': user_debates, "get_friends" : get_friends}
        return render(request, self.template_name, args)


def add_comment_to_post(request, pk):
    debate = get_object_or_404(DebateTopic, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.debate = debate
            comment.author = request.user
            comment.save()
            return redirect('debate:detail', pk=debate.pk)
    else:
        form = CommentForm()
    return render_to_response('debate/create_comment.html', {'form': form}, request)



def profile_edit(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/debate/profile')

    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'debate/profile_edit.html', args)

def change_friends(request, operation, pk):
    new_friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, new_friend)
    elif operation == 'remove':
        Friend.remove_friend(request.user, new_friend)
    return redirect('debate:profile')

def search_titles(request):
    debate_names = SearchQuerySet().autocomplete(content_auto=request.POST.get('search_text', ''))

    return render_to_response('debate/ajax_search.html', {'debate_names' : debate_names})

debate/templates/debate/ajax_search.html
{% if debate_names.count > 0 %}

{% for debate in debate_names %}
    <li><a href="{{ debate.object.get_absolute_url }}">{{ debate.object.topic }}</a></li>
{% endfor %}

{% else %}

<li>No debates with this name found!</li>

{% endif %}

debate/templates/debate/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Debate It</title>{% endblock %}
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Change val of family to load new font from google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Syncopate" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script  src="{% static 'debate/js/jquery-3.2.1.js' %}"></script>
    <script  src="{% static 'debate/js/ajax.js' %}"></script>
    <link rel="stylesheet"  href="{% static 'debate/css/style.css' %}"/>
</head>
<body>
    <nav class="navbar" id="navbarAll">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{%  url 'debate:index' %}">
                        <a href="{%  url 'debate:login' %}">
                            <img class="deb-im" src="{% static 'debate/images/debate_it_words_white.png' %}" height="60px"/>
                        </a>
                    </a>
                {% else %}
                <a href="{%  url 'debate:login' %}"><img class="deb-im" src="{% static 'debate/images/debate_it_words_white.png' %}" height="50px"/></a>
                {% endif %}
            </div>

            <!-- Items -->

            <div class="collapse navbar-collapse" id="topNavBar">

                {% if user.is_authenticated %}

                <div class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <div class="input-group pull-right">
                            {% csrf_token %}
                            <input type="text" class="form-control" id="search" name="search" value=""/>
                            <ul id="search-results">

                            </ul>
                            <div class="input-group-btn">
                                <button type="submit" class="btn"><div class="glyphicon glyphicon-search"></div> </button>
                            </div>
                        </div>
                    </div>
                </div>

                <ul class="nav navbar-nav navbar-right" id="navi">

                    <li class="">
                        <a href="{%  url 'debate:profile' %}" class="color-me">
                            <span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>&nbsp; My Profile
                        </a>
                    </li>
                    <li class="">
                        <a href="{%  url 'debate:index' %}" class="color-me">
                            <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>&nbsp; Featured Debates
                        </a>
                    </li>
                    <li class="" id="create-debate-nav">
                        <a href="{% url 'debate:debate-topic-add' %}" class="color-me" data-toggle="modal" data-target="#create-debate-modal">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Create Debate
                        </a>
                        <div class="modal fade" tabindex="-1" role="dialog" id="create-debate-modal">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title">Modal title</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>One fine body&hellip;</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div>
                    </li>
                    <li class="">
                        <a href="{% url 'debate:logout' %}" class="color-me">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log Out
                        </a>
                    </li>
                </ul>

                {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'debate:login' %}" class="color-me">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Log In
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'debate:register' %}" class="color-me">
                            <span class="glyphicon glyphicon-road" aria-hidden="true"></span>&nbsp; Register
                        </a>
                    </li>
                </ul>
                {% endif %}

            </div>

        </div>
    </nav>
{#    <script type="text/javascript">#}
{#        $(document).ready(function () {#}
{#            $('#create-debate-nav').click(function () {#}
{#                $('create-debate-modal').modal('show');#}
{#            });#}
{#        });#}
{#    </script>#}
{% block body %}
{% endblock %}
</body>
</html>

debate/templates/debate/create_comment.html
<h1>New comment</h1>
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Send</button>
</form>

debate/templates/debate/debatetopic_form.html
<div class="modal-header"><h4>Create a debate</h4></div>
<form class="form-horizontal modal-body" action="{% url 'debate:debate-topic-add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'debate/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>
<div class="modal-footer">
    <button class="btn btn-danger" data-dismiss="modal">Close</button>
</div>

debate/templates/debate/detail.html
{% extends 'debate/base.html' %}

{% block title %}<title>Debate Details</title>{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="panel">
            <ul class="nav nav-tabs">
                <li>
                    <a href="#det-debate-topic" data-toggle="tab" class="'">Debate Info</a>
                </li>
                <li>
                    <a href="#det-comments" data-toggle="tab">Comments</a>
                </li>
                <li>
                    <a href="#det-articles" data-toggle="tab">Articles</a>
                </li>
            </ul>

            <ul class="tab-content">
                <li id="det-debate-topic" class="tab-pane active" >
                    <h1>Debate: {{ debatetopic.topic }}</h1>
                    <h3>Description: {{ debatetopic.description }}</h3>
                    <ul><h4>Topic Tags:</h4>
                        {% for tag in debatetopic.tags %}
                            <li>
                                <p>{{ tag }}</p>
                            </li>
                        {% endfor %}
                    </ul>
                </li>

                <li id="det-comments" class="tab-pane">
                    <div class="row">
                        <div class="col-md-8 ">
                            <div class="container-fluid">
                                {% load comments static %}
                                <link rel="stylesheet" type="text/css" href="{% static 'fluent_comments/css/ajaxcomments.css' %}" />
                                <script type="text/javascript" src="{% static 'fluent_comments/js/ajaxcomments.js' %}"></script>
                                {% render_comment_form for debate.debatetopic debatetopic.id %}
                                {% render_comment_list for debate.debatetopic debatetopic.id %}
                            </div>

{#                            <a href="{% url 'debate:comment-add' pk=debatetopic.pk%}"> Add comment</a>#}
{##}
{#                            <form method="post" enctype="multipart/form-data" id="myForm">#}
{#                                {% csrf_token %}#}
{#                                <div class="form-group">#}
{#                                    <label>Share your voice!</label>#}
{#                                    <input type="text" class="form-control" id="comment-input" placeholder="Comment">#}
{#                                    <button class="btn btn-primary" type="submit">Post</button>#}
{#                                </div>#}
{#                            </form>#}
{#                            <script>#}
{#                                // wait for the DOM to be loaded#}
{#                                $(document).ready(function() {#}
{#                                    // bind 'myForm' and provide a simple callback function#}
{#                                    $('#myForm').ajaxForm(function() {#}
{#                                        alert("Thank you for your comment!");#}
{#                                    });#}
{#                                });#}
{#                            </script>#}
                        </div>
                    </div>

{#                    {% for comment in debatetopic.points.all %}#}
{#                    <div class="row">#}
{#                        <div class="col-md-1 ">#}
{#                            <div>#}
{#                                <img id="comment-img" class="img-responsive img-circle" src="{{ comment.author.userprofile.image.url }}">#}
{#                            </div><!-- /thumbnail -->#}
{#                        </div><!-- /col-sm-1 -->#}
{##}
{#                        <div class="col-md-6">#}
{#                            <div class="panel panel-default">#}
{#                                <div class="panel-heading">#}
{#                                    <strong>{{ comment.author.first_name }} {{ comment.author.last_name }}</strong>#}
{#                                    <span class="text-muted">commented on {{ comment.created_date }}</span>#}
{#                                    <button class="btn btn-primary">Good Point! <span class="badge">{{ comment.good_points }}</span></button>#}
{#                                    <button class="btn btn-danger" type="button">Unclear <span class="badge">{{ comment.bad_points }}</span></button>#}
{#                                </div>#}
{#                                <div class="panel-body">#}
{#                                    {{ comment.claim|linebreaks }}#}
{#                                </div><!-- /panel-body -->#}
{#                            </div><!-- /panel panel-default -->#}
{#                        </div><!-- /col-sm-5 -->#}
{#                    </div>#}
{##}
{#                    {% empty %}#}
{#                        <p>Be the first to spark this debate!</p>#}
{#                    {% endfor %}#}
                </li>
                <li id="det-articles" class="tab-pane">
                    <h1>Articles</h1>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

debate/templates/debate/find_friends.html
{% extends 'debate/base.html' %}

{% block body %}

    {% if object_list %}

            {% for person in object_list %}
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="thumbnail">
                                <p><a href = "/debate/profile/{{ person.id }}">{{ person.first_name }} {{ person.last_name }}</a></p>
                                <a href="/debate/connect/add/{{ person.id }}/" class="btn btn-success" role="button">Add Friend</a></p>
                            </div>
                        </div>
                    </div>
                </div>

            {% endfor %}
    {% else %}
        <div class="alert alert-danger" id="alertNoTopics">There are no friends to find!</div>
    {% endif %}

{% endblock %}

debate/templates/debate/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

debate/templates/debate/logout.html
{% extends 'debate/base.html' %}

{% block title %}<title>Debates Logout</title>{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="jumbotron">
            <h1>Logged out</h1>
            <p>
                You have logged out! See you later!
            </p>
        </div>
    </div>
{% endblock %}